Parameters:
  Repo:
    Description: The GitHub organization/repo for which the OIDC provider is set up
    Type: String
    Default: Ajay263/nexabrands-supply-chain

Resources:
  MyOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd

  topdevs2025Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${Repo}:*
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
      Policies:
        - PolicyName: dbtRedshiftAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - redshift-data:ExecuteStatement
                  - redshift-data:GetStatementResult
                  - redshift-data:DescribeStatement
                  - redshift-data:CancelStatement
                  - redshift-data:ListStatements
                  - redshift:DescribeClusters
                  - redshift:GetClusterCredentials
                  - redshift-serverless:GetCredentials
                  - redshift-serverless:ListWorkgroups
                  - redshift-serverless:GetWorkgroup
                  - redshift-serverless:ListNamespaces
                  - redshift-serverless:GetNamespace
                Resource: '*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub arn:aws:secretsmanager:*:${AWS::AccountId}:secret:topdevs-*
                  - !Sub arn:aws:secretsmanager:*:${AWS::AccountId}:secret:dbt-*

        - PolicyName: dbtEC2Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:StartInstances
                  - ec2:StopInstances
                  - ec2:RebootInstances
                  - ssm:SendCommand
                  - ssm:GetCommandInvocation
                  - ssm:ListCommandInvocations
                  - ssm:DescribeInstanceInformation
                Resource: '*'
                Condition:
                  StringLike:
                    aws:ResourceTag/Name: topdevs-*-dbt-instance

        - PolicyName: dbtSSMParameters
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:PutParameter
                Resource:
                  - !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/topdevs-*
                  - !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/dbt-*

        - PolicyName: GlueManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:*
                Resource: '*'

        - PolicyName: GlueCrawlerManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartCrawler
                  - glue:StopCrawler
                  - glue:GetCrawler
                  - glue:GetCrawlers
                  - glue:UpdateCrawler
                  - glue:DeleteCrawler
                  - glue:CreateCrawler
                  - glue:ListCrawlers
                Resource: '*'
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetPartitions
                  - glue:GetUserDefinedFunctions
                Resource: '*'

        - PolicyName: VPCEndpointManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateVpcEndpoint
                  - ec2:DeleteVpcEndpoints
                  - ec2:DescribeVpcEndpoints
                  - ec2:ModifyVpcEndpoint
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource: '*'
              - Effect: Allow
                Action:
                  - ec2:CreateSecurityGroup
                  - ec2:DeleteSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:RevokeSecurityGroupEgress
                Resource: '*'
                Condition:
                  StringLike:
                    aws:ResourceTag/Name:
                      - topdevs-*-endpoint-sg
                      - topdevs-*-vpc-endpoint-sg

        - PolicyName: VPCManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateVpc
                  - ec2:DeleteVpc
                  - ec2:CreateSubnet
                  - ec2:DeleteSubnet
                  - ec2:CreateRouteTable
                  - ec2:DeleteRouteTable
                  - ec2:CreateRoute
                  - ec2:DeleteRoute
                  - ec2:AssociateRouteTable
                  - ec2:DisassociateRouteTable
                  - ec2:CreateInternetGateway
                  - ec2:DeleteInternetGateway
                  - ec2:AttachInternetGateway
                  - ec2:DetachInternetGateway
                  - ec2:CreateNatGateway
                  - ec2:DeleteNatGateway
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - ec2:DescribeVpcs
                  - ec2:DescribeSubnets
                  - ec2:DescribeRouteTables
                  - ec2:DescribeInternetGateways
                  - ec2:DescribeNatGateways
                  - ec2:DescribeAvailabilityZones
                Resource: '*'
                Condition:
                  StringLike:
                    aws:ResourceTag/Name: topdevs-*

        - PolicyName: S3BucketManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:PutBucketPolicy
                  - s3:DeleteBucketPolicy
                  - s3:GetBucketPolicy
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::topdevs-*
                  - !Sub arn:aws:s3:::topdevs-*/*
                  - !Sub arn:aws:s3:::nexabrands-*
                  - !Sub arn:aws:s3:::nexabrands-*/*

        - PolicyName: TerraformStateManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::topdevs-tf-backend/*
                  - arn:aws:s3:::topdevs-tf-backend
                  - arn:aws:s3:::nexabrands-tf-backend
                  - arn:aws:s3:::nexabrands-tf-backend/*
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                Resource:
                  - !Sub arn:aws:dynamodb:*:${AWS::AccountId}:table/topdevsTerraformLocks

        - PolicyName: RedshiftServerlessManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - redshift-serverless:*
                  - redshift:*
                  - redshift-data:ExecuteStatement
                  - redshift-data:GetStatementResult
                  - redshift-data:DescribeStatement
                  - redshift:GetClusterCredentials
                  - redshift:DescribeClusters
                Resource: '*'
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRolePolicy
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:TagRole
                  - iam:UntagRole
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/topdevs-*-redshift-serverless-role
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/topdevs-*-glue-service-role
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/topdevs-*-ec2-role

        - PolicyName: S3EndpointAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource:
                  - !Sub arn:aws:s3:::topdevs-*
                  - !Sub arn:aws:s3:::topdevs-*/*
              - Effect: Allow
                Action:
                  - ec2:CreateVpcEndpoint
                  - ec2:DeleteVpcEndpoints
                  - ec2:DescribeVpcEndpoints
                Resource: '*'
                Condition:
                  StringLike:
                    aws:ResourceTag/Name: topdevs-*-s3-endpoint

        - PolicyName: EC2InstanceProfileManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateInstanceProfile
                  - iam:DeleteInstanceProfile
                  - iam:GetInstanceProfile
                  - iam:AddRoleToInstanceProfile
                  - iam:RemoveRoleFromInstanceProfile
                  - iam:ListInstanceProfilesForRole
                Resource: !Sub arn:aws:iam::${AWS::AccountId}:instance-profile/*

        - PolicyName: IAMRoleManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRolePolicy
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:ListAttachedRolePolicies
                  - iam:ListRolePolicies
                  - iam:TagRole
                  - iam:UntagRole
                  - iam:CreatePolicy
                  - iam:DeletePolicy
                  - iam:GetPolicy
                  - iam:GetPolicyVersion
                  - iam:ListPolicyVersions
                  - iam:CreatePolicyVersion
                  - iam:DeletePolicyVersion
                  - iam:SetDefaultPolicyVersion
                  - iam:ListInstanceProfilesForRole
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/topdevs-*
                  - !Sub arn:aws:iam::${AWS::AccountId}:policy/topdevs-*
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/nexabrands-*
                  - !Sub arn:aws:iam::${AWS::AccountId}:policy/nexabrands-*

Outputs:
  RoleName:
    Description: The name of the IAM role for GitHub Actions
    Value: !Ref topdevs2025Role
    Export:
      Name: !Sub ${AWS::StackName}-RoleName
  RoleARN:
    Description: The ARN of the IAM role for GitHub Actions
    Value: !GetAtt topdevs2025Role.Arn
    Export:
      Name: !Sub ${AWS::StackName}-RoleARN