data_source nexabrands:
    type: redshift
    host: nexabrands-redshift-workgroup.313142695879.us-east-1.redshift-serverless.amazonaws.com
    username: admin
    password: Password123!
    database: nexabrands_datawarehouse
    schema: nexabrands_external
    region: us-east-1

soda_cloud:
  host: cloud.us.soda.io
  api_key_id: ca1c8e29-d584-4b11-8d42-c13f7aabbb34
  api_key_secret: tmrrRrcauAWfeGlUb1-x0vsRx6gkk2szEgpY9-Tapj2xSallEtlh5g



