name: 'nexabrands_dbt'
version: '1.0.0'

vars:
  dbt_date:
    time_zone: "UTC"

profile: 'nexabrands_dbt'

flags:
  require_explicit_package_overrides_for_builtin_materializations: False
  

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nexabrands_dbt:
    +materialized: view
    +persist_docs:
      relation: true
      columns: true
    +hours_to_expiration: 168
    +schema: nexabrands_dbt
    staging:
      +materialized: table
      +schema: staging
      # Updated configuration for CSV external sources
      +external_location: "s3://nexabrands-prod-target/"
      +file_format: csv
      +row_format: >
       serde 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
       with serdeproperties (
              'separatorChar'=','
            )
      +table_properties: "('skip.header.line.count'='1')"
    marts:
      +materialized: table
      +schema: marts
  elementary:
    +schema: elementary

tests:
  nexabrands_dbt:
    +severity: warn
    marts:
      +severity: error
