
nexabrands_dbt:
  outputs:
    prod:
      type: redshift
      host: nexabrands-redshift-workgroup.057116.us-east-1.redshift-serverless.amazonaws.com
      user: dbt690
      password: YourSecurePassw
      port: 5439
      dbname: nexabrands_datawarehouse
      schema: nexabrands_dbt
      threads: 4
      keepalives_idle: 0
      connect_timeout: 60
  target: prod

