# airflow/dbt/nexabrands_dbt/profiles.yml
prod:
  target: prod
  outputs:
    prod:
      type: redshift

      port: 5439
      dbname: nexabrands_datawarehouse
      user: "{{ env_var('REDSHIFT_USER') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      # Add these for IAM access
      method: iam
      iam_profile: default
      region: us-east-1
      cluster_identifier: nexabrands-redshift-workgroup