# nexabrands_dbt:
#   target: dev
#   outputs:
#     dev:
#       type: redshift
#       host: 
#       user: admin
#       password: Password123!
#       port: 5439
#       dbname: nexabrands_datawarehouse
#       schema: nexabrands_external
#       threads: 4

nexabrands_dbt:
  outputs:
    prod:
      type: redshift
      host: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_HOST') }}"  
      user: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_USER') }}" 
      password: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_PASSWORD') }}"    
      port: 5439
      dbname: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_DATABASE') }}"   
      schema: "{{ env_var('DBT_ENV_SECRET_REDSHIFT_SCHEMA') }}" 
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
  target: prod
    

    