
nexabrands_dbt:
  target: prod
  outputs:
    prod:
      type: redshift
      host: <redshift host>
      user: <redshift username>
      password: <redshift password>
      port: 5439
      dbname: nexabrands_datawarehouse
      schema: nexabrands_dbt
      threads: 4
      keepalives_idle: 0
      connect_timeout: 60

    pr:
      type: redshift
      host:  <redshift host>
      user: admin
      password: Password123!
      port: 5439
      dbname: nexabrands_datawarehouse
      schema: pr_{{ var('schema_id') }}
      threads: 4
      keepalives_idle: 0
      connect_timeout: 60
