name: AIRFLOW TEST

on:
  pull_request:
    branches:
      - '*'   # Triggers on PRs to any branch

jobs:
  test-and-comment:
    runs-on: self-hosted  # This example uses a hosted runner; update if you need a self-hosted one
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install  pytest pytest-cov allure-pytest pre-commit boto3 awscli pytest-rerunfailures pandas numpy
          
      - name: Install and run pre-commit hooks
        run: |
              pre-commit install
              SKIP=sqlfluff-lint,sqlfluff-fix,yamllint,no-commit-to-branch pre-commit run --all-files --verbose

      - name: Run tests with coverage
        run: |
          # For instance, if your tests run on a Dockerized Airflow service:
          sudo docker exec airflow-airflow-webserver-1 bash -c "pytest --cache-clear --cov=/opt/airflow/dags --cov-report=term-missing /opt/airflow/test/ > pytest-coverage.txt"
          # Adjust the --cov parameter as necessary for your project
        
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          pytest-coverage: pytest-coverage.txt
