name: PR Coverage Comment
on:
  pull_request:
    branches: [ '*' ]

jobs:
  pytest-coverage:
    runs-on: self-hosted  # Matches your shosted runner setup
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests and generate coverage inside Docker
        run: |
          sudo docker exec airflow-airflow-webserver-1 bash -c "pytest --cov=/opt/airflow/dags /opt/airflow/test/ -v -p no:warnings > /opt/airflow/pytest-coverage.txt"

      - name: Copy coverage report from container
        run: |
          sudo docker cp airflow-airflow-webserver-1:/opt/airflow/pytest-coverage.txt ./pytest-coverage.txt

      - name: Comment coverage on PR
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          pytest-coverage: pytest-coverage.txt
