name: Trigger Airflow DAG
on:
  push:
    branches:
      - main
jobs:
  trigger-airflow:
    runs-on: self-hosted  # Use self-hosted runner on your EC2 instance
    
    # Add permissions for commenting on PRs
    permissions:
      contents: write
      checks: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest pytest-cov allure-pytest pre-commit boto3 awscli pytest-rerunfailures pandas numpy
          
      - name: Install and run pre-commit hooks
        run: |
              pre-commit install
              SKIP=sqlfluff-lint,sqlfluff-fix,yamllint,no-commit-to-branch pre-commit run --all-files --verbose
    
      
      - name: Check environment
        run: |
          pwd
          ls -la
          sudo docker ps -a  # List all containers with sudo
      
      - name: Install pytest-cov in Docker container
        run: |
          sudo docker exec airflow-airflow-webserver-1 pip install pytest-cov
      
      - name: Test the Airflow dag with coverage
        run: |
          # Run tests with coverage and generate reports
          sudo docker exec airflow-airflow-webserver-1 bash -c "cd /opt/airflow && python -m pytest -v test/ -p no:warnings --junitxml=/opt/airflow/pytest.xml --cov=opt.airflow --cov-report=term > /opt/airflow/pytest-coverage.txt"
      
      - name: Copy coverage files from Docker container
        run: |
          sudo docker cp airflow-airflow-webserver-1:/opt/airflow/pytest.xml ./pytest.xml || echo "pytest.xml not found"
          sudo docker cp airflow-airflow-webserver-1:/opt/airflow/pytest-coverage.txt ./pytest-coverage.txt || echo "pytest-coverage.txt not found"
      
      - name: Pytest coverage comment
        id: coverage-comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
