name: Airflow CI Workflow

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
    paths:
      - 'airflow/dag/**'
      - 'airflow/test/**'
      - 'airflow/Dockerfile'
      - 'requirements.txt'
      - 'requirements_dbt_venv.txt'
  pull_request:
    paths:
      - 'airflow/dag/**'
      - 'airflow/test/**'
      - 'airflow/Dockerfile'
      - 'requirements.txt'
      - 'requirements_dbt_venv.txt'
  workflow_dispatch:

env:
  TEST_EXECUTION_ENV: prod

jobs:
  test:
    name: 'Run Airflow Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug directory structure
        run: |
          ls -la
          ls -la airflow || echo "airflow directory not found"
          find airflow -type f -name "Dockerfile" | sort
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Airflow Test Image
        uses: docker/build-push-action@v5
        with:
          context: ./airflow
          file: ./airflow/Dockerfile
          load: true
          tags: airflow-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test Docker image
        run: |
          docker run --rm airflow-test:latest bash -c "echo 'Testing Docker image'"
      
      - name: Install Test Dependencies in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app airflow-test:latest bash -c "python -m pip install pytest pytest-cov allure-pytest pytest-rerunfailures pre-commit"
      
      - name: Run Pre-commit in Docker
        continue-on-error: true
        run: |
          if [ -f ".pre-commit-config.yaml" ]; then
            docker run --rm -v ${{ github.workspace }}:/app -w /app airflow-test:latest bash -c "cd /app && git init && git add . && pre-commit install && SKIP=sqlfluff-lint,sqlfluff-fix,yamllint,no-commit-to-branch pre-commit run --all-files --verbose"
          else
            echo "No pre-commit config found, skipping"
          fi
      
      - name: Run Airflow Tests in Docker
        id: run_tests
        continue-on-error: true
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e PYTHONPATH=/app/airflow/dag \
            airflow-test:latest \
            bash -c "cd /app/airflow/test && python -m pytest -xvs --continue-on-collection-errors --reruns 3 --cov=../dag --cov-report=xml:coverage.xml --cov-report=html:coverage_html --alluredir=allure-results"
      
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Upload Coverage Report (HTML)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage_html
          path: airflow/test/coverage_html
      
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: airflow/test/allure-results
      
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: airflow/test/allure-results
          allure_history: allure-history
      
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
      
      - name: Deploy to GitHub Pages
        if: always() && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          keep_files: false
      
      - name: Check test exit code
        if: always()
        id: check_status
        run: |
          if [ "${{ steps.run_tests.outcome }}" == "failure" ]; then
            echo "tests_failed=true" >> $GITHUB_OUTPUT
          else
            echo "tests_failed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Fail if tests failed
        if: steps.check_status.outputs.tests_failed == 'true'
        run: |
          echo "Tests failed. Marking workflow as failed."
          exit 1
