name: Redshift Connection Test

on:
  workflow_dispatch:

jobs:
  test-redshift:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # This should be your OIDC role ARN
          aws-region: us-east-1
      
      - name: Install AWS CLI
        run: |
          pip install awscli
      
      - name: Test Redshift Connection
        run: |
          # Get workgroup endpoint
          ENDPOINT=$(aws redshift-serverless get-workgroup --workgroup-name nexabrands-redshift-workgroup --query 'workgroup.endpoint.address' --output text)
          echo "Redshift endpoint: $ENDPOINT"
          
          # Test with a simple query
          aws redshift-data execute-statement \
            --workgroup-name nexabrands-redshift-workgroup \
            --database nexabrands_datawarehouse \
            --sql "SELECT current_date;"