name: DBT CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - development
      full_refresh:
        description: 'Run with full refresh'
        required: false
        default: false
        type: boolean

jobs:
  dbt_ci_cd_job:
    environment: ${{ github.event.inputs.environment || 'production' }}
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: .
      S3_BUCKET_PATH: ${{ secrets.CODE_BUCKET }}
    permissions:
      id-token: write 
      contents: read 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Using 3.10 for better compatibility with dbt packages

      - name: Install dependencies
        run: |
          pip install -r airflow/requirements_dbt_venv.txt
          pip install dbt-redshift==1.8.1 awscli psycopg2-binary

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-east-1
          
      - name: Get Redshift Workgroup Endpoint
        id: get-endpoint
        run: |
          ENDPOINT=$(aws redshift-serverless get-workgroup --workgroup-name nexabrands-redshift-workgroup --query 'workgroup.endpoint.address' --output text)
          echo "REDSHIFT_ENDPOINT=${ENDPOINT}" >> $GITHUB_ENV
          echo "Retrieved Redshift endpoint: ${ENDPOINT}"

      - name: Create profiles.yml
        run: |
          cat > airflow/dbt/nexabrands_dbt/profiles.yml <<EOF
          nexabrands_dbt:
            outputs:
              prod:
                type: redshift
                host: ${REDSHIFT_ENDPOINT}
                user: ${{ secrets.DBT_ENV_SECRET_REDSHIFT_USER }}
                password: ${{ secrets.DBT_ENV_SECRET_REDSHIFT_PASSWORD }}
                port: ${{ secrets.DBT_ENV_SECRET_REDSHIFT_PORT }}
                dbname: ${{ secrets.DBT_ENV_SECRET_REDSHIFT_DATABASE }}
                schema: ${{ secrets.DBT_ENV_SECRET_REDSHIFT_SCHEMA }}
                threads: 4
                keepalives_idle: 0
                connect_timeout: 120
                retries: 3
            target: prod
          EOF
          
          # Debug - print the profiles.yml without credentials
          cat airflow/dbt/nexabrands_dbt/profiles.yml | sed 's/\(password: \).*/\1***/' | sed 's/\(host: \).*/\1***/'
      
      - name: Prepare S3 for dbt artifacts
        run: |
          aws s3api head-bucket --bucket ${{ secrets.CODE_BUCKET }} || aws s3 mb s3://${{ secrets.CODE_BUCKET }}
          aws s3 ls s3://${{ secrets.CODE_BUCKET }}/dbt-docs/ || aws s3api put-object --bucket ${{ secrets.CODE_BUCKET }} --key dbt-docs/
          
      - name: Download previous manifest for slim CI
        run: |
          echo "Downloading manifest from s3://${{ secrets.CODE_BUCKET }}/dbt-docs/manifest.json"
          aws s3 cp s3://${{ secrets.CODE_BUCKET }}/dbt-docs/manifest.json ./manifest.json || echo "No previous manifest found"

      - name: Run dbt debug
        working-directory: airflow/dbt/nexabrands_dbt
        run: |
          dbt --version
          dbt debug --target prod

      - name: Run dbt deps
        working-directory: airflow/dbt/nexabrands_dbt
        run: dbt deps --target prod

      - name: Run dbt test (PR only - Slim CI)
        if: github.event_name == 'pull_request'
        working-directory: airflow/dbt/nexabrands_dbt
        run: |
          if [ -f "../../manifest.json" ]; then
            echo "Running slim CI tests on modified models only"
            dbt test --select state:modified+ --defer --state ../../ --target prod
          else
            echo "No previous manifest found, running all tests"
            dbt test --target prod
          fi

      - name: Run dbt build (main branch or manual dispatch - Slim CI)
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        working-directory: airflow/dbt/nexabrands_dbt
        run: |
          if [ "${{ github.event.inputs.full_refresh }}" == "true" ]; then
            echo "Running with full refresh"
            dbt build --full-refresh --target prod
          elif [ -f "../../manifest.json" ] && [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            echo "Running slim CI build on modified models only"
            dbt build --select state:modified+ --defer --state ../../ --target prod
          else
            echo "Running normal build"
            dbt build --target prod
          fi

      - name: Generate dbt docs
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        working-directory: airflow/dbt/nexabrands_dbt
        run: dbt docs generate --target prod

      - name: Upload manifest and docs to S3
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: |
          aws s3 cp airflow/dbt/nexabrands_dbt/target/manifest.json s3://${{ secrets.CODE_BUCKET }}/dbt-docs/
          aws s3 cp airflow/dbt/nexabrands_dbt/target/catalog.json s3://${{ secrets.CODE_BUCKET }}/dbt-docs/
          aws s3 cp airflow/dbt/nexabrands_dbt/target/index.html s3://${{ secrets.CODE_BUCKET }}/dbt-docs/
          
      - name: Verify uploads
        if: (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch') && success()
        run: |
          echo "Verifying uploads..."
          aws s3 ls s3://${{ secrets.CODE_BUCKET }}/dbt-docs/ || echo "Upload verification failed!"