name: CD_action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CD_job:
    runs-on: self-hosted
    environment: production
    permissions:
      id-token: write
      contents: read
    env:
      S3_MANIFEST_BUCKET: "nexabrands-prod-target"
      S3_MANIFEST_KEY: "dbt-docs/manifest.json"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r airflow/requirements_dbt_venv.txt

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-east-1


      - name: Test Redshift Connectivity
        run: |
          echo "Testing connection to $REDSHIFT_ENDPOINT:5439"
          nc -vz nexabrands-redshift-workgroup.043309357116.us-east-1.redshift-serverless.amazonaws.com 5439

      - name: Set up dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cp ./airflow/dbt/nexabrands_dbt/profiles.yml ~/.dbt/profiles.yml

      - name: Download manifest.json from S3
        working-directory: airflow/dbt/nexabrands_dbt
        run: |
          aws s3 cp s3://${{ env.S3_MANIFEST_BUCKET }}/${{ env.S3_MANIFEST_KEY }} ./manifest.json || echo "Manifest not found"

      - name: Run dbt debug
        working-directory: airflow/dbt/nexabrands_dbt
        run: dbt debug --target prod

      - name: Run dbt deps
        working-directory: airflow/dbt/nexabrands_dbt
        run: dbt deps --target prod

      - name: Run dbt build
        working-directory: airflow/dbt/nexabrands_dbt
        run: |
          if [ -f "./manifest.json" ]; then
            dbt build -s 'state:modified+' --state ./ --target prod
          else
            dbt build --target prod
          fi

      - name: Upload new manifest.json to S3
        working-directory: airflow/dbt/nexabrands_dbt
        run: |
          aws s3 cp ./target/manifest.json s3://${{ env.S3_MANIFEST_BUCKET }}/${{ env.S3_MANIFEST_KEY }}