name: Deploy Schema Change Job

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/modules/scripts/schema_change.py'
      - '.github/workflows/deploy-schema-change.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'modules/scripts/schema_change.py'

permissions:
  id-token: write
  contents: read

env:
  TF_STATE_BUCKET: "topdevs-tf-backend"
  TF_STATE_LOCK_TABLE: "topdevsTerraformLocks"
  AWS_REGION: "us-east-1"
  ENVIRONMENT: prod 
jobs:
  deploy:
    name: Deploy Schema Change Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1  # Hardcoded to match Terraform backend

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 pytest

      - name: Upload schema change script to S3
        run: |
          aws s3 cp modules/scripts/schema_change.py "s3://nexabrands-${ENVIRONMENT}-code/scripts/"


      - name: Deploy Schema Change Job
        run: |
          aws glue update-job \
            --job-name "topdevs-${ENVIRONMENT}-schema-change-job" \
            --job-update '{
              "Role": "'"${GLUE_ROLE_ARN}"'",
              "Command": {
                "Name": "pythonshell",
                "ScriptLocation": "s3://nexabrands-'"${ENVIRONMENT}"'-code/scripts/schema_change.py",
                "PythonVersion": "3"
              },
              "GlueVersion": "4.0",
              "Timeout": 2880,
              "MaxRetries": 1,
              "DefaultArguments": {
                "--enable-continuous-cloudwatch-log": "true",
                "--enable-metrics": "true",
                "--job-language": "python"
              }
            }'